export const APP_INIT = 'APP_INIT';
export const APP_INIT_ERROR = 'APP_INIT_ERROR';
export const PHONE_SAVE_REQUEST = 'PHONE_SAVE_REQUEST';
export const PHONE_SAVE_SUCCESS = 'PHONE_SAVE_SUCCESS';
export const PHONE_SAVE_FAILED = 'PHONE_SAVE_FAILED';
export const PHONE_DELETE_REQUEST = 'PHONE_DELETE_REQUEST';
export const PHONE_DELETE_SUCCESS = 'PHONE_DELETE_SUCCESS';
export const PHONE_DELETE_FAILED = 'PHONE_DELETE_FAILED';
